name: CI

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: tinygfx
        submodules: recursive

    - name: Setup environment
      run: |
        echo "$PWD/build/install/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=$PWD/build/install/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        bash tinygfx/etc/Linux/linux-setup-gha.sh

    - name: Build
      run: bash tinygfx/etc/Linux/linux-build-gha.sh Debug

  macos-12-build:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v4
      with:
        path: tinygfx
        submodules: recursive

    # \bug DYLD_LIBRARY_PATH is not being set here?
    - name: Setup environment
      run: |
        echo "$PWD/build/install/bin" >> $GITHUB_PATH
        echo "DYLD_LIBRARY_PATH=$PWD/build/install/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        cmake --version

    - name: Build
      run: |
        export DYLD_LIBRARY_PATH=$PWD/build/install/lib:$DYLD_LIBRARY_PATH
        bash tinygfx/etc/macOS/macos-build-gha.sh Debug

  macos-14-build:
    runs-on: macos-14

    env:
      CMAKE_OSX_DEPLOYMENT_TARGET: 14
      CMAKE_OSX_ARCHITECTURES: arm64

    steps:
    - uses: actions/checkout@v4
      with:
        path: tinygfx
        submodules: recursive

    # \bug DYLD_LIBRARY_PATH is not being set here?
    - name: Setup environment
      run: |
        echo "$PWD/build/install/bin" >> $GITHUB_PATH
        echo "DYLD_LIBRARY_PATH=$PWD/build/install/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
        cmake --version

    - name: Build
      run: |
        export DYLD_LIBRARY_PATH=$PWD/build/install/lib:$DYLD_LIBRARY_PATH
        bash tinygfx/etc/macOS/macos-build-gha.sh Debug

  windows-build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: tinygfx
        submodules: recursive

    # \bug Any spaces before the ">>" will be considered part of the path.
    - name: Setup environment
      shell: cmd
      run: |
        echo %CD%\build\install\bin>> %GITHUB_PATH%
        echo %CD%\build\install\lib>> %GITHUB_PATH%
        echo CTEST_OUTPUT_ON_FAILURE=1 >> %GITHUB_ENV%
        cmake --version

    - name: Build
      shell: cmd
      run: |
        tinygfx\etc\Windows\windows-build-gha.bat Debug
